name: CI on push
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run build
      run: |
       docker build . --tag ghcr.io/t-d-h/docker-busybox:latest
       docker push ghcr.io/t-d-h/docker-busybox:latest